In [1]:
import numpy as np

In [95]:
mat = [[0.1, 0.2, 0.3, 0.4],
        [0.5, 0.6, 0.7, 0.8],
        [0.9, 0.10, 0.11, 0.12],
        [0.13, 0.14, 0.15, 0.16]]

In [96]:
pow20 = np.array(mat)
for i in range(19):
    pow20 = pow20 @ np.array(mat)

In [99]:
pow20.round(3)

array([[17.947, 11.41 , 14.022, 16.633],
       [49.864, 31.703, 38.959, 46.214],
       [19.887, 12.644, 15.537, 18.431],
       [11.37 ,  7.229,  8.883, 10.538]])

In [21]:
import re

In [100]:
pow20.tolist()

[[17.946559294256257,
  11.410130900671799,
  14.021570582771655,
  16.633010264871515],
 [49.86399001833409, 31.702714933427075, 38.95852369922412, 46.21433246502119],
 [19.88672748979092,
  12.643658326344699,
  15.537415757251974,
  18.43117318815925],
 [11.369885146648977,
  7.228788299893762,
  8.883242993212907,
  10.537697686532052]]

In [91]:
p = re.compile('[0-9]{6}\.[0-9]{7}')

In [92]:
p.findall("""[[205484.73359354 205485.0419355  205485.09636622 205483.87679454]
 [247793.0649692  247788.98905078 247791.7909668  247788.29554393]
 [269949.91738191 269949.7830116  269948.85042288 269952.4653867 ]
 [325348.28405535 325352.18600212 325350.26224409 325351.36227483]]""")

['205484.733',
 '205485.041',
 '205485.096',
 '205483.876',
 '247793.064',
 '247788.989',
 '247791.790',
 '247788.295',
 '269949.917',
 '269949.783',
 '269948.850',
 '269952.465',
 '325348.284',
 '325352.186',
 '325350.262',
 '325351.362']

In [93]:
round(4.5555,3)

4.556

In [108]:
# set matrices A, B
aMat = [[3, 1, 4],
        [1, 5, 9],
        [2, 6, 5]]

bMat = [[3, 5, 8],
        [9, 7, 9],
        [3, 2, 3]]

# set initial value
cMat = [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]

# Write the matrix-matrix multiplication C = A * B

for i in range(3):
    for j in range(3):
        for k in range(3):
            cMat[i][j] = cMat[i][j] + aMat[i][k] * bMat[k][i]

# print matrix C
for i in range(3):
    for j in range(3):
        print(cMat[i][j], end = ' ')
    print()

30 30 45 
75 58 80 
75 62 85 
